apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-final
  labels:
    app: flask-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-final
  # pod spec begins here
  template:
    metadata:
      labels:
        app: flask-final
    spec:
      containers:
        - name: flask-final
          image: registry.digitalocean.com/final/jaredburks/final:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000